providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install ."]

[start]
cmd = "python -m uvicorn app.api:app --app-dir src --host 0.0.0.0 --port $PORT"
